## MTskR config
## https://github.com/ryanpeng69/mtskr/

# This language will be used on the messages in console
console_lang: en_us

# The block limit of a model, should not be too small.
model_maxium_blocks: 1000

# The gap of how long the train will detect for passengers at the door to get on the train in ticks.
tick_for_ride_train_detection: 2